# Generated by Django 6.0.4 on 2026-04-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='dep_name',
            new_name='dept_name',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='doc_imade',
            new_name='doc_image',
        ),
    ]
